### ISSUE TITLE
Error: Cannot find module '%USERPROFILE%\Downloads\tradfri-flux\new.js'

### ISSUE THREAD

**Issue by babbysross** [overwatchcorp/tradfri-flux#1]
>After running the setup.js file, npm start fails due to the above error, full error log pasted below:

![image](https://user-images.githubusercontent.com/30228233/45000812-e0cdd400-afbf-11e8-8b6f-8003614f8597.png)

**Comment by babbysross** [comment]
For more info, here is the log file:

>0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.1.0
3 info using node@v10.7.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle tradfri-test@1.0.0\~prestart: tradfri-test@1.0.0
6 info lifecycle tradfri-test@1.0.0\~start: tradfri-test@1.0.0
7 verbose lifecycle tradfri-test@1.0.0\~start: unsafe-perm in lifecycle true
8 verbose lifecycle tradfri-test@1.0.0\~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;%USERPROFILE%\Downloads\tradfri-flux\node_modules\.bin;%USERPROFILE%\Software\cmder\bin;%USERPROFILE%\Software\cmder\vendor\conemu-maximus5\ConEmu\Scripts;%USERPROFILE%\Software\cmder\vendor\conemu-maximus5;%USERPROFILE%\Software\cmder\vendor\conemu-maximus5\ConEmu;C:\Program Files\ImageMagick-7.0.8-Q16;C:\Program Files (x86)\Python37-32\Scripts\;C:\Program Files (x86)\Python37-32\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\nodejs\;C:\WINDOWS\System32\OpenSSH\;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;%USERPROFILE%\AppData\Roaming\npm;C:\Program Files\ImageMagick-7.0.8-Q16;C:\Program Files (x86)\Midnight Commander;C:\Program Files\Git\mingw64;%USERPROFILE%\Software\cmder
9 verbose lifecycle tradfri-test@1.0.0\~start: CWD: %USERPROFILE%\Downloads\tradfri-flux
10 silly lifecycle tradfri-test@1.0.0\~start: Args: [ '/d /s /c', 'node new.js' ]
11 silly lifecycle tradfri-test@1.0.0\~start: Returned: code: 1  signal: null
12 info lifecycle tradfri-test@1.0.0\~start: Failed to exec start script
13 verbose stack Error: tradfri-test@1.0.0 start: `node new.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid tradfri-test@1.0.0
15 verbose cwd %USERPROFILE%\Downloads\tradfri-flux
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.7.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error tradfri-test@1.0.0 start: `node new.js`
22 error Exit status 1
23 error Failed at the tradfri-test@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by wokhouse** [comment]
This should be fixed--it was due to an incorrect filename in "main" in package.json
